# Site settings
title: Weather No Wrong
email: 467318976@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: 看样子记录一下感想还是十分必要的
aboutme_photo: /img/aboutme_photo.jpg

# Social icons
github: jeffssss


footer: 码农一枚，没了

# Build settings
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
